import Head from "next/head";
import Filter from "../components/Filter";
import ProductItem from "../components/ProductItem";
import ProductList from "../components/ProductList";
import classes from "./Home.module.scss";
import { useEffect, useContext } from "react";
import { Context } from "../context";

export default function Home({ data }) {
  const { productData, setProductData, displayProducts, setDisplayProducts } =
    useContext(Context);

  useEffect(() => {
    setProductData(data);
    setDisplayProducts(data)
    console.log(productData);
  }, [productData, data]);

  return (
    <div className={classes.bg}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.contain}>
        <Filter />
        <div className={classes.main}>
          <h1>Edvora</h1>
          <h3>Products</h3>
          <ProductList productData={displayProducts} />
          <ProductList productData={displayProducts} />
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const response = await fetch("https://assessment-edvora.herokuapp.com/");
  const data = await response.json();

  return {
    props: {
      data,
    },
  };
}
